### ISSUE TITLE
Boats and mounting entities disabled in modpack with latest update.

### ISSUE THREAD

**Issue by yamhwee** [SoSly/ArcaneAdditions#78] opened 2024-04-01 15:10 UTC
When I use the latest update of Arcane Additions in my modpack I can no longer enter vanilla boats, snowy spirit sleds, small ships ships, or astikor cart redux carts. Inexperienced with modded and as such, I'm not sure what I ought to send to you to help with the problem or if it's a problem a larger group is experiencing. I expect the problem is in fact due to an incompatibility interaction between mods in my environment and not necessarily a problem specific to Arcane Additions.

**Comment by nivthefox** [comment] 2024-04-15 20:16
Can you confirm what version of Arcane Additions you have installed?

**Comment by nivthefox** [comment] 2024-05-17 06:03
@yamhwee I am unable to reproduce this on Arcane Additions 1.9.3.  If I don't hear more information from you before I release 1.9.4/1.10, I will be closing this as cannot reproduce.  Please let me know if you can provide any further information!

**Closed as completed** 2024-06-24 15:28 UTC
